name: go-tests-temp

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test-main-workflow

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: go test ./...
